version: '3'
services:
  postgres:
    image: postgres:9-alpine
    container_name: postgres
    env_file:
      - psql.env
    ports:
    - '5432:5432'
    volumes: 
    - ./postgres_data:/var/lib/postgresql/data
  binance:
    image: data_colector
    build: ./data_colector
    container_name: data_colector
    restart: always
    env_file:
      - collector.env
      - psql.env
    volumes:
    - ${PWD}/data_colector:/data_colector
    
volumes:
  postgres_data: