version: '3'
services:
  postgres:
    image: postgres:9-alpine
    container_name: postgres
    restart: always
    env_file:
      - psql.env
    ports:
    - '5432:5432'
    volumes: 
    - ./postgres_data:/var/lib/postgresql/data
  collector:
    image: data_collector
    build: ./data_collector
    container_name: collector
    env_file:
      - collector.env
      - psql.env
    
volumes:
  postgres_data: